# Generated by Django 4.1.5 on 2023-05-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domainModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='HintPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.CharField(default="", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalitiesLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.DecimalField(decimal_places=2, max_digits=6)),
                ('i', models.DecimalField(decimal_places=2, max_digits=6)),
                ('s', models.DecimalField(decimal_places=2, max_digits=6)),
                ('n', models.DecimalField(decimal_places=2, max_digits=6)),
                ('t', models.DecimalField(decimal_places=2, max_digits=6)),
                ('f', models.DecimalField(decimal_places=2, max_digits=6)),
                ('j', models.DecimalField(decimal_places=2, max_digits=6)),
                ('p', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalitiesNames',
            fields=[
                ('personalityName', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PracticalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SolveTrying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField()),
                ('studentKnowledge', models.ManyToManyField(to='domainModel.paragraphdata')),
            ],
        ),
        migrations.CreateModel(
            name='TimePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.DecimalField(decimal_places=3, max_digits=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentModel.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TheoreticalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.IntegerField()),
                ('self_rate', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('generalConcept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainModel.generalconcept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentModel.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solve_date', models.DateTimeField(null=True)),
                ('solutionCode', models.TextField(null=True)),
                ('used_concept_difficulty', models.IntegerField(null=True)),
                ('hint_levels', models.CharField(default='', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainModel.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentModel.studentprofile')),
            ],
        ),
    ]
