# Generated by Django 4.1.5 on 2023-05-30 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domainModel', '0001_initial'),
        ('studentModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solvetrying',
            name='student_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentModel.studentproject'),
        ),
        migrations.AddField(
            model_name='practicalskill',
            name='generalConcept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainModel.generalconcept'),
        ),
        migrations.AddField(
            model_name='practicalskill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentModel.studentprofile'),
        ),
        migrations.AddField(
            model_name='personalitiesletters',
            name='personalityName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentModel.personalitiesnames'),
        ),
        migrations.AddField(
            model_name='personalitiesletters',
            name='studentProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentModel.studentprofile'),
        ),
        migrations.AddField(
            model_name='hintperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentModel.studentprofile'),
        ),
        migrations.AddField(
            model_name='difficultyperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentModel.studentprofile'),
        ),
    ]
