# Generated by Django 4.1.5 on 2023-03-10 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentModel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalitiesletters',
            name='personalityName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentModel.personalitiesnames'),
        ),
        migrations.AddField(
            model_name='personalitiesletters',
            name='studentProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentModel.studentprofile'),
        ),
    ]
