# Generated by Django 4.2.2 on 2023-07-30 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConcept',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('concept_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correctAnswerSample', models.TextField()),
                ('output', models.TextField()),
                ('explanation', models.TextField()),
                ('hint', models.TextField(null=True)),
                ('img_src', models.TextField(null=True)),
                ('generalConcepts', models.ManyToManyField(related_name='projects', to='domainModel.generalconcept')),
            ],
        ),
        migrations.CreateModel(
            name='SubConcept',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('generalConcept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainModel.generalconcept')),
            ],
        ),
        migrations.CreateModel(
            name='QuizzesQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correctAnswer', models.TextField()),
                ('generalConcept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainModel.generalconcept')),
            ],
        ),
        migrations.CreateModel(
            name='QuizzesAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainModel.quizzesquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 7, 30, 13, 23, 51, 530492))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainModel.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_concept_hint', models.CharField(default='', max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 7, 30, 13, 23, 51, 530492))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainModel.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 7, 30, 13, 23, 51, 530492))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainModel.project')),
            ],
        ),
        migrations.CreateModel(
            name='ParagraphData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subheading', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('nb', models.TextField(null=True)),
                ('img_src', models.TextField(null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainModel.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='subConcept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainModel.subconcept'),
        ),
        migrations.CreateModel(
            name='ExampleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_text', models.TextField()),
                ('example', models.TextField()),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_data', to='domainModel.paragraphdata')),
            ],
        ),
        migrations.CreateModel(
            name='CodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_text', models.TextField()),
                ('code', models.TextField()),
                ('output', models.TextField()),
                ('codeExplanation', models.TextField()),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_data', to='domainModel.paragraphdata')),
            ],
        ),
    ]
