# Generated by Django 4.1.5 on 2023-03-22 19:36
import csv
import re

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):
    def load_data(apps, schema_editor):
        GeneralConcept = apps.get_model('domainModel', 'GeneralConcept')
        QuizzesQuestion = apps.get_model('domainModel', 'QuizzesQuestion')
        QuizzesAnswers = apps.get_model('domainModel', 'QuizzesAnswers')
        with open('Nouvil_Quizzes.csv', encoding='utf-8') as f:
            reader = csv.reader(f)
            next(reader)
            i = 0
            for row in reader:
                i += 1

                generalconcept = GeneralConcept.objects.get(name=row[0])
                question = QuizzesQuestion.objects.create(
                    generalConcept=generalconcept,
                    question=row[1],
                    correctAnswer=row[3],
                )
                answers_list = row[2]
                if re.match(r'^\s*\[.*\]\s*$', answers_list):
                    # Field value is a list
                    list_value = eval(answers_list)  # Use eval() to parse the list
                    for item in list_value:
                        answer = QuizzesAnswers.objects.create(
                            question=question,
                            answer=item,
                        )
                        # print(f"answer {i} loaded!")
                # print(f"question {i} loaded!")

    dependencies = [
        ('domainModel', 'add_projects'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
