# Generated by Django 4.1.5 on 2023-03-22 19:36
import csv
import re

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def load_data(apps, schema_editor):
        MbtiQuestions = apps.get_model('gamificationModel', 'MbtiQuestions')
        MbtiAnswers = apps.get_model('gamificationModel', 'MbtiAnswers')
        with open('mbti_test.csv', encoding='utf-8') as f:
            reader = csv.reader(f)
            next(reader)
            i = 0
            for row in reader:
                i += 1
                print(row, i)
                question = MbtiQuestions.objects.create(
                    question_text=row[0],
                )
                # answers_list = row[1]
                # if re.match(r'^\s*\[.*\]\s*$', answers_list):
                #     # Field value is a list
                #     list_value = eval(answers_list)  # Use eval() to parse the list
                #     for item in list_value:
                answer = MbtiAnswers.objects.create(
                    question=question,
                    answer=row[1],
                )
                answer = MbtiAnswers.objects.create(
                    question=question,
                    answer=row[2],
                )

                        # print(f"answer {i} loaded!")
                # print(f"question {i} loaded!")

    dependencies = [
        ('gamificationModel', 'add_featurePersonalityRelationship'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
